### ISSUE TITLE
Needle Diameter

### ISSUE THREAD

**Issue by MOImaker** [jdber1/opendrop#12]
A simple question:
When the program asks for "Needle Diameter (mm)", is this outer diameter or inner diameter?

Thanks

**Comment by ricotabor** [comment]
Outer diameter, as this is what is seen in the image (and used to calibrate
the spatial dimensions of the image).

:)

---
*Rico TABOR  *
Senior Lecturer
ARC Future Fellow

*School of Chemistry*
Monash University
Room G24B
19 Rainforest Walk
Clayton VIC 3800
Australia

T: +61 3 9905 4558
M: +61 (0)414 327 313
E: rico.tabor@monash.edu
W: ricotabor.com
Calendar: goo.gl/V9yjba

Download the latest version of OpenDrop from opencolloids.com

**Comment by MOImaker** [comment]
Thanks very much!
