### ISSUE TITLE
Can't run for windows10, python 2.7

### ISSUE THREAD

**Issue by MuchuZhou** [jdber1/opendrop#15]
Hi I got this issue below. 
![error](https://user-images.githubusercontent.com/51695875/59252138-a0535480-8be8-11e9-940d-3a6cd87d6a9a.jpg)
Help, please.

**Comment by askoufis** [comment]
There should be a file called `de_YoungLaplace.py` in the modules directory, so I'm sure why you're getting that error. Have you followed the instructions for setting up OpenDrop on your version on Windows? https://github.com/jdber1/opendrop#appendix-b

**Comment by ogarland** [comment]
I am having the same issue, I have checked that `de_YoungLaplace.py` is in the modules directory. Has anything else come of this?

**Comment by eugenhu** [comment]
Closing to inactive/old issue.
