### ISSUE TITLE
issue with SFs

### ISSUE THREAD

**Issue by nllwrdobrn** [jdber1/opendrop#20]
Thanks for making this great program!  

The IFT values the program calculates are displayed in-app to 4 SF, but in the exported csv file only 3 are visible.  Is there some way of resolving this problem and getting a .csv with the full 4 significant figures?

Many thanks!

Niall

**Comment by eugenhu** [comment]
Thanks for the feedback. Currently this seems to be an inconsistency with the user interface. I've only been responsible with programming the overall UI itself and haven't looked too deeply into the numerical analysis that's performed, but I believe any more than 3 s.f. might be overly precise considering the errors with the fitting procedure. In that sense, I suppose it's more of the app showing more s.f. than appropriate.

**Comment by nllwrdobrn** [comment]
Ah, okay!  Thanks for the speedy reply.

**Comment by eugenhu** [comment]
I think the UI now just shows 3 s.f.
