### ISSUE TITLE
Installation/run issue on Ubuntu 18.04

### ISSUE THREAD

**Issue by ricotabor** [jdber1/opendrop#26]
System is fresh install of Ubuntu 18.04.5

Pip3 is newest version, git is installed, OpenDrop installation appears to work, but this is the terminal output:

![IMG_20201127_130730](https://user-images.githubusercontent.com/12204959/100556607-94d17d00-32f7-11eb-99b7-ad8422076cfb.jpg)

Any idea what I've done wrong this time? :)

**Comment by eugenhu** [comment]
That's weird, I thought I had fixed this in a previous commit. I've just installed Python 3.6.12 on my machine and managed to start opendrop with no issues.

Could you check the version of python installed on your ubuntu system with `python3 --version`

Also just to confirm, for the installation did you run
```
pip install git+https://github.com/jdber1/opendrop.git
```
?

**Comment by ricotabor** [comment]
I can check when I'm next in the lab, but Python version will be whatever ships with Ubuntu 18.04LTS: I think it's 3.6.8 maybe?

I think the regular install command didn't work for some reason (again, can find the specific error soon if useful), but:

pip install opendrop-3.1.7.dev54+gb1534f0-py3-none-any.whl

seemed to install without error, but then gave the error above when trying to run.

**Comment by eugenhu** [comment]
Oh, the `opendrop-3.1.7.dev54+gb1534f0-py3-none-any.whl` wheel was for an older version, when you're able to, could you try
```
pip install git+https://github.com/jdber1/opendrop.git
```
to install the latest version from the repo instead?

**Comment by ricotabor** [comment]
Thanks Eugene, will give it a go when I'm back in the lab (probably Friday again) and report back!

**Comment by ricotabor** [comment]
> pip3 install git+https://github.com/jdber1/opendrop.git

Fails with error below. Python3 --version is 3.6.9

Any ideas on what to fix? 

![IMG_20201204_095925765](https://user-images.githubusercontent.com/12204959/101099027-0e2edf80-3618-11eb-91c5-c25c4b2be4a5.jpg)

**Comment by eugenhu** [comment]
Could you try updating pip and setuptools?
pip3 install -U pip setuptools
And try reinstalling again, if it fails could you send the pip version.

**Comment by ricotabor** [comment]
Eugenius! Adding setuptools did work (also needed python3-opencv for anyone reading).

However, it's still very laggy when using genicam to run the camera. The live video window is fine, but actually running the calculations causes a stall after first ~20 seconds. For reference, I requested 5 frames, 20 seconds apart in the below. Not sure if the terminal errors are related?

![IMG_20201204_103207376](https://user-images.githubusercontent.com/12204959/101104750-f22f3c00-361f-11eb-989f-f5209c180309.jpg)
![IMG_20201204_103141430](https://user-images.githubusercontent.com/12204959/101104752-f3606900-361f-11eb-99fc-78b3968f0c8a.jpg)

**Comment by eugenhu** [comment]
I see, thanks for the feedback. I'm currently working out some of the performance issues by offloading some of the work to separate processes so the UI won't stall.

Those errors I think are just some numpy deprecation warnings that didn't used to be there, relating to making arrays with different length rows.

**Comment by ricotabor** [comment]
Sounds amazing, can't wait to hear more. Thank you for the fast and positive updates :)
