### ISSUE TITLE
OpenDrop 3.2 run issue on Ubuntu 20.04

### ISSUE THREAD

**Issue by ricotabor** [jdber1/opendrop#27]
Thank you so much for the new version/updates! I'm getting the error below when I try and run after installing the new version on Ubuntu 20.04. Might be something very obvious I've done wrong of course! Many thanks in advance.

![IMG_20210205_112141510](https://user-images.githubusercontent.com/12204959/106975357-80ec4080-67aa-11eb-912c-3e560a0b55c5.jpg)

**Comment by eugenhu** [comment]
Yep sorry, that's my bad. I've added something that broke compatibility with older versions of python again. Should be fixed now if you could try pip install again.

**Comment by ricotabor** [comment]
Can confirm that this fixes the run issue, and the new version now runs like a dream. Video and fitting all happens in real-time with no lag. Incredible! Thank you!

We will be in touch with any minor feature requests once we've had a chance to test more thoroughly.

**Comment by eugenhu** [comment]
No problems, thank you for the feedback.
