### ISSUE TITLE
IFT gets inaccurate with certain needle selection boxes

### ISSUE THREAD

**Issue by FelixKratz** [jdber1/opendrop#29]
It seems if the needle region is a bit too large the needle width estimate gets highly inconsistent. For an example see the attached image. It can be circumvented by selecting a smaller region. 

A tooltip in the app could possibly help with confusions?
![cap_width](https://user-images.githubusercontent.com/22680421/107400538-2f251c80-6b02-11eb-96b5-cb25f40f13ef.png)

**Comment by eugenhu** [comment]
This should be improved by https://github.com/jdber1/opendrop/commit/ac371ad8815f6c99369713bf4369a3bbfcbb8f13 .
