### ISSUE TITLE
Rounding values

### ISSUE THREAD

**Issue by jh-guo** [jdber1/opendrop#35]
Hello, thanks for this amazing work! As shown in the figure, I was trying to get the IFT for my interfacial experiments and got the values rounded off automatically. I was just wondering how I can get IFT values accurate to two decimal places? Thanks!
![Image](https://user-images.githubusercontent.com/88688205/128777724-cdd461e2-0e3c-4305-845f-8b736d9f43ed.png)

**Comment by eugenhu** [comment]
Hello,

Thank you for the feedback. Unfortunately the number of decimal places displayed and saved is currently fixed. It was previously decided by rule of thumb that 3 sig. figs is probably sufficient, gauging the errors present in this sort of image analysis. However it looks like you're trying to compare IFT values across a series of photos, so as a workaround for now I've just hardcoded the app to show and save 4 s.f. instead (https://github.com/jdber1/opendrop/commit/6b3ca36eae3740645e8984b290bb896ee3a6cf5a). 

You can get the updated version on the releases page:
https://github.com/jdber1/opendrop/releases/tag/v3.3.1

In the future, we plan on adding some kind of standard error calculation for the estimated fit quantities (e.g. IFT, contact angle).
