### ISSUE TITLE
problem installing OpenDrop on MacOS

### ISSUE THREAD

**Issue by osleland** [jdber1/opendrop#41]
I'm having trouble installing OpenDrop at [step 4 of the tutorial](https://opendrop.readthedocs.io/en/latest/installation/index.html?highlight=anaconda). I've successfully downloaded opencv-python, pygobject3 gtk+3, and SUNDIALS but have trouble with Boost.Math. When I tried to run the command brew install Boost.Math, the command was unknown and the only equivalent I found was brew install boost-mpi and brew install boost (which is updated to boost 1.79.0). That seems to have installed successfully, but once I run the command pip install git+https://github.com/jdber1/opendrop.git it will crash while "Preparing wheel metadata..." I've attached the details of the crash/error in the pdf file, as it won't let me attach a txt file. 
[OpenDrop_error.pdf](https://github.com/jdber1/opendrop/files/9072454/OpenDrop_error.pdf)

I'm running on macOS Big Sur version 11.6.4 and run python on Anaconda 2.2.0. That may be the root of the issue here.

**Comment by eugenhu** [comment]
Do you know what version of SUNDIALS you have installed? There was an api change in version 6. I've updated the code in the development branch to use the newer api if you want to try installing from that:
```
pip install git+https://github.com/jdber1/opendrop.git@development
```

**Comment by osleland** [comment]
The Kernel keeps dying and gives me a MacOS crash log with
> Exception Type:        EXC_BAD_ACCESS (SIGSEGV)
Exception Codes:       KERN_INVALID_ADDRESS at 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY
>
>Termination Signal:    Segmentation fault: 11
Termination Reason:    Namespace SIGNAL, Code 0xb
Terminating Process:   exc handler [85593]


Is the problem that I'm using gtk+3 3.24.34?

**Comment by eugenhu** [comment]
That Gtk version looks fine. There might be a problem with the anaconda package. You could try installing all the dependencies using Homebrew instead if you're not tied down to anaconda.

I believe the Homebrew packages you need are:
- [python@3.8](https://formulae.brew.sh/formula/python@3.8)
- [boost](https://formulae.brew.sh/formula/boost)
- [sundials](https://formulae.brew.sh/formula/sundials)
- [gtk+3](https://formulae.brew.sh/formula/gtk+3)
- [pygobject3](https://formulae.brew.sh/formula/pygobject3)
- [opencv](https://formulae.brew.sh/formula/opencv) with python bindings (I think you install with `--with-python3`)

**Comment by eugenhu** [comment]
I see, no problems. Hopefully we can provide standalone binaries on macOS and linux too in the future.
