### ISSUE TITLE
Interfacial Tension fails with sundials 6.4.1:  ARKODE::ERKStep ERROR

### ISSUE THREAD

**Issue by drew-parsons** [jdber1/opendrop#46]
opendrop 3.3.1 fails to build with sundials 6.  The build is "fixed" by commit cf9d5aa in development branch.
I'm building from the debian source for opendrop 3.3.1, after adding the cf9d5aa patch. I succeed building against sundials 6.4.1 (which provides arkode 5.4.1). 

But after applying that patch, sundials (arkode) still fails at runtime. It is used when analysing a droplet for Interfacial Tension, making a Young-Laplace model of the shape (opendrop/fit/younglaplace/shape.pyx, using include/opendrop/younglaplace_detail.hpp)

After setting the Drop Region and Needle Region in the image of the drop and pressing the "Analyse" button, it gives this error:
```
[ARKODE::ERKStep ERROR]  erkStep_FullRHS
  At t = inf, the right-hand side routine failed in an unrecoverable manner.


[ARKODE ERROR]  ARKODE
  At t = 0, the right-hand side routine failed in an unrecoverable manner.

Exception in callback PendantAnalysisJob._ylfit_done(<Future finis...e() failed.')>)
handle: <GLibSourceHandle PendantAnalysisJob._ylfit_done(<Future finis...ylfit_done()]>)>
concurrent.futures.process._RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/usr/lib/python3.11/concurrent/futures/process.py", line 256, in _process_worker
    r = call_item.fn(*call_item.args, **call_item.kwargs)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3/dist-packages/opendrop/fit/younglaplace/__init__.py", line 51, in young_laplace_fit
    model.set_params(initial_params)
  File "/usr/lib/python3/dist-packages/opendrop/fit/younglaplace/model.py", line 86, in set_params
    dr_dBo, dz_dBo = radius * shape.DBo(s)
                              ^^^^^^^^^^^^
  File "opendrop/fit/younglaplace/shape.pyx", line 71, in opendrop.fit.younglaplace.shape.YoungLaplaceShape.DBo
  File "opendrop/fit/younglaplace/shape.pyx", line 88, in opendrop.fit.younglaplace.shape.YoungLaplaceShape.DBo_array
RuntimeError: ERKStepEvolve() failed.
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/opendrop/vendor/aioglib/_loop.py", line 463, in __call__
    self._context.run(self._callback, *self._args)
  File "/usr/lib/python3/dist-packages/opendrop/app/ift/services/analysis.py", line 219, in _ylfit_done
    raise e
  File "/usr/lib/python3/dist-packages/opendrop/app/ift/services/analysis.py", line 217, in _ylfit_done
    result = fut.result()
             ^^^^^^^^^^^^
RuntimeError: ERKStepEvolve() failed.
```

**Comment by eugenhu** [comment]
Strange, can you share the drop image and I'll try running the analysis on my computer.

Also, can you try cloning the repo (`development` branch) and installing `cython` and [`SCons`](https://pypi.org/project/SCons/), and then running `scons` in the repo's root directory to build the C tests for the Young-Laplace solver. Then try running `test_interpolate` and `test_younglaplace` in the 'tests/c/' directory to make sure they work.

Thanks.

**Comment by drew-parsons** [comment]
The error seems to always occur, any image. This one reproduces the problem.:
https://github.com/jdber1/opendrop/blob/bf5ad09e792063806a9894a48e41c21c928f3a52/tests/samples/images/image0.png

I'll try the C tests.  Python tests passed already.

**Comment by eugenhu** [comment]
Thanks for testing. I'll need to do some experimenting myself later to reproduce this.

**Comment by drew-parsons** [comment]
For comparison, the Debian build logs are found at https://buildd.debian.org/status/package.php?p=opendrop
e.g. https://buildd.debian.org/status/fetch.php?pkg=opendrop&arch=amd64&ver=3.3.1-4%2Bb1&stamp=1675071543&raw=0
They add some other build flags (e.g. `-D_FORTIFY_SOURCE=2 -fstack-protector-strong`), but `tests/c` still passes if I added them to a manual C test build.

**Comment by eugenhu** [comment]
I'm thinking this might be the culprit:

https://github.com/jdber1/opendrop/blob/e18fbf3d7d6f94d02f4846400be518a56b86e73c/include/opendrop/younglaplace_detail.hpp#L637

https://github.com/jdber1/opendrop/blob/e18fbf3d7d6f94d02f4846400be518a56b86e73c/include/opendrop/younglaplace_detail.hpp#L650-L651

A bit of a hack to regularize singularities at the initial value. Possibly you could try changing this to:
```
INFINITESIMAL = std::numeric_limits<realtype>::min(); 
```
or `INFINITESIMAL = 1e-10`. I think I also overlooked testing "DBo()" in the c tests, which is where its crashing.

**Comment by eugenhu** [comment]
Ok, thanks for testing. Turns out the problem was a silly mistake introduced many commits ago, you can check https://github.com/jdber1/opendrop/commit/2f7dc0eda952eb4a1024fba480f1c9f547cc5829 for bug detail.

Could you try reinstalling the development branch to see if it's resolved on your end too?
