### ISSUE TITLE
Possible configuration of OpenDrop in a commercial instrument

### ISSUE THREAD

**Issue by Cristiano1974a** [jdber1/opendrop#52]
Dears, I'm Cristiano Albonetti, a senior researcher from Italian national research council (CNR). I work with a contact angle meter from GBX (https://gbxonline.com/contact-angle) but now something goes wrong in the instrument communication and nobody in the company help me (probably because the instrument is old and they want sell a new one). I would know if the software OpenDrop, in principle, can control any contact angle (clearly with a proper configuration). At the same time, I will work with an Italian electronic company to repair the electronics. Let me know and thanks in advanced for any help.
Best regards
Cristiano

**Comment by eugenhu** [comment]
OpenDrop is mainly only used for analysing pre-acquired images, or live capturing from a camera. It depends on what interface the camera on your contact angle meter uses to communicate with the computer, e.g. GenICam. There is also no support in OpenDrop for controlling a needle to dispense liquid, moving around a base plate and so on.

I also don't have time to work on this project anymore, so I can provide guidance if someone would like to adapt this program for your needs but to answer your question, I don't think OpenDrop will do what you need out of the box unfortunately.
