### ISSUE TITLE
Trying to run a script - what is the error?/colorize.pyx file

### ISSUE THREAD

**Issue by Kaiman777** [jdber1/opendrop#53]
Hello. I tried to run the script from the message "Run Opendrop without GUI, but from command line/python", but an error occurs,
-------------------------------------------
Traceback (most recent call last):
 File "C:\opendrop-3.3.1_source\opendrop-3.3.1\opendrop_script_example.py", line 6, in <module>
 from opendrop.features.pendant import extract_pendant_features
 File "C:\opendrop-3.3.1_source\opendrop-3.3.1\opendrop\features\__init__.py", line 1, in <module>
 from .colorize import *
ModuleNotFoundError: No module named 'opendrop.features.colorize'
-------------------------------------------------- -------------
Complains about the colorize.pyx file. Trying to rename it to colorize.py didn't help. Please tell me what could be the problem?

**Comment by eugenhu** [comment]
That script works if you installed opendrop using pip. From your error message, it looks like you're trying to run it with Windows which is not easy to get opendrop installed from source. You could maybe try using Windows Subsystem for Linux? But I don't have experience with that unfortunately.

The .pyx file is a Cython source file that needs to be compiled by Cython to C and then compiled by a C compiler, this is kind of a pain to do on Windows. And then there are other issues with getting opendrop running on Windows which I've had to debug recently.

**Comment by Kaiman777** [comment]
Thanks for the info.
